services:
  db:
    image: postgres:15
    container_name: church_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: churchdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: node:20
    container_name: backend
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./config:/app/config
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./package-lock.json:/app/package-lock.json
    working_dir: /app
    command: >
      sh -c "
        npm install &&
        npx nest build &&
        npx nest start --watch
      "
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: churchdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      AUTH0_DOMAIN: dev-ohuspam6fnmh4tgt.us.auth0.com
      AUTH0_AUDIENCE: logger
      AUTH0_ISSUER: https://dev-ohuspam6fnmh4tgt.us.auth0.com/
      JWT_SECRET: "your_jwt"

volumes:
  postgres_data:
