FROM node:20-alpine AS base
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

############################
FROM base AS dev
CMD ["npm", "run", "start:dev"]

############################
FROM node:20-alpine AS prod
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=base /app/dist ./dist
COPY --from=base /app/migrations ./migrations
ENV NODE_ENV=production
USER node
CMD ["node", "dist/src/main.js"]
