FROM node:20 AS base

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build || (echo "Build failed" && exit 1)

############################
FROM base AS dev
COPY --from=base /app/dist ./dist
COPY --from=base /app/node_modules ./node_modules
CMD ["npm", "run", "start:dev"]

############################
FROM base AS prod
USER node
COPY --from=base /app/dist ./dist
CMD ["node", "dist/main.js"]
