FROM node:20 AS base

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

############################
FROM base AS dev
USER node
COPY --from=base /app/dist ./dist
CMD ["npm", "run", "start:dev"]

############################
FROM base AS prod
USER node
COPY --from=base /app/dist ./dist
CMD ["node", "dist/main.js"]
