version: '3.8'

services:
  db:
    image: postgres:15
    container_name: church_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: churchdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: backend
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start:dev
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: churchdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      AUTH0_DOMAIN: dev-ohuspam6fnmh4tgt.us.auth0.com
      AUTH0_AUDIENCE: logger
      AUTH0_ISSUER: https://dev-ohuspam6fnmh4tgt.us.auth0.com/

volumes:
  postgres_data:
